#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : usbredir
Version  : 0.8.0
Release  : 16
URL      : http://spice-space.org/download/usbredir/usbredir-0.8.0.tar.bz2
Source0  : http://spice-space.org/download/usbredir/usbredir-0.8.0.tar.bz2
Summary  : usbredirparser library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0+ LGPL-2.1
Requires: usbredir-bin
Requires: usbredir-lib
Requires: usbredir-license
Requires: usbredir-man
BuildRequires : pkgconfig(libusb-1.0)

%description
---------------
usbredir is a protocol for redirection USB traffic from a single USB device,
to a different (virtual) machine then the one to which the USB device is
attached. See usb-redirection-protocol.txt for the description / definition
of this protocol.

%package bin
Summary: bin components for the usbredir package.
Group: Binaries
Requires: usbredir-license
Requires: usbredir-man

%description bin
bin components for the usbredir package.


%package dev
Summary: dev components for the usbredir package.
Group: Development
Requires: usbredir-lib
Requires: usbredir-bin
Provides: usbredir-devel

%description dev
dev components for the usbredir package.


%package lib
Summary: lib components for the usbredir package.
Group: Libraries
Requires: usbredir-license

%description lib
lib components for the usbredir package.


%package license
Summary: license components for the usbredir package.
Group: Default

%description license
license components for the usbredir package.


%package man
Summary: man components for the usbredir package.
Group: Default

%description man
man components for the usbredir package.


%prep
%setup -q -n usbredir-0.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533653656
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1533653656
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/usbredir
cp COPYING %{buildroot}/usr/share/doc/usbredir/COPYING
cp COPYING.LIB %{buildroot}/usr/share/doc/usbredir/COPYING.LIB
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/usbredirserver

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libusbredirhost.so
/usr/lib64/libusbredirparser.so
/usr/lib64/pkgconfig/libusbredirhost.pc
/usr/lib64/pkgconfig/libusbredirparser-0.5.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libusbredirhost.so.1
/usr/lib64/libusbredirhost.so.1.0.1
/usr/lib64/libusbredirparser.so.1
/usr/lib64/libusbredirparser.so.1.0.1

%files license
%defattr(-,root,root,-)
/usr/share/doc/usbredir/COPYING
/usr/share/doc/usbredir/COPYING.LIB

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/usbredirserver.1
